ls_german = [
    "Vier Jahre Trump und der Angriff auf das Herz der amerikanischen Demokratie zeigen: Rechtspopulisten an der Macht entzaubern sich nicht. Das muss eine Lehre für uns alle sein. \n~Baerbock",
    "Deutschland ist ein Problem, weil die Deutschen fleißiger, disziplinierter und begabter als der Rest Europas sind. Das wird immer wieder zu ‘Ungleichgewichten’ führen. Dem kann aber gegengesteuert werden, indem so viel Geld wie nur möglich aus Deutschland herausgeleitet wird. Es ist vollkommen egal wofür, es kann auch radikal verschwendet werden – Hauptsache, die Deutschen haben es nicht. Schon ist die Welt gerettet.\n~Joschka Fischer",
    "Noch nie habe ich die deutsche Nationalhymne mitgesungen und ich werde es als Minister auch nicht tun. \n~Jürgen Trittin",
    "Deutschland muss von außen eingehegt, und von innen durch Zustrom von Ausländern heterogenisiert, quasi verdünnt werden.\n~Joschka Fischer",
    "Deutsche sind ‚Nicht-Migranten‘ - mehr nicht! …die Türkei ist zweite Heimat für mich, ich mache seit 20 Jahren Türkei-Politik.\n~Claudia Roth",
    "Wir kennen Euren inneren Zustand. Dafür haben wir einen Blick und die nötige Sensibilität. Und da wir Euch kennen, werden wir uns auf Euch nicht mehr verlassen. Wir gehen unseren Weg und der ist schmerzlich und voller Dornen, aber am Ende erfolgreich… - Ihr habt nur die Chance, mit uns zu leben. Ein Leben ohne uns wird es für Euch nicht mehr geben. Die Ibrahims, Stefanos, Marios, Laylas und Sorayas sind deutsche Realität.... - Ihr werdet es nicht verhindern können, dass bald ein türkischstämmiger Richter über Euch das Urteil fällt, ein pakistanischer Arzt Eure Krankheiten heilt, ein Tamile im Parlament Eure Gesetze mit verabschiedet…. Nicht Ihr werdet die Gesellschaft modernisieren… und humanisieren, sondern wir werden es tun für Euch! - Ihr seid bei diesem leidvollen Prozess lediglich Zaungäste, lästige Gaffer! Wir werden die deutsche Gesellschaft in Ost und West verändern!\n~M. Walid Nakschbandi",
    "Es geht nicht um Recht oder Unrecht in der Einwanderungsdebatte, uns geht es zuerst um die Zurückdrängung des deutschen Bevölkerungsanteils in diesem Land!\n~Vorstand der Grünen",
    "Deutschland verschwindet jeden Tag immer mehr, und das finde ich einfach großartig.\n~Jürgen Trittin",
    "Ich wollte, daß Frankreich bis zur Elbe reicht und Polen direkt an Frankreich grenzt.\n~Sieglinde Frieß",
    "Migration ist in Frankfurt eine Tatsache. Wenn Ihnen das nicht passt, müssen Sie woanders hinziehen\n~Nargess Eskandari-Grünberg",
    "Sinngemäß: Wir, die Grünen, müssen dafür sorgen, so viele Ausländer wie möglich nach"
    "Deutschland zu holen. Wenn sie in Deutschland sind, müssen wir für ihr Wahlrecht kämpfen. Wenn wir das erreicht haben, werden wir den Stimmenanteil haben, den wir brauchen, um diese Republik zu verändern.\n~Daniel Cohn-Bendit",
    "Deutsche Helden müsste die Welt, tollwütigen Hunden gleich, einfach totschlagen.\n~Joschka Fischer",
    "Die Abschaffung der Eidesformel “Zum Wohle des deutschen Volkes” wird im NRW-Landtag einstimmig beschlossen.\n~Arif Ünal",
    "Die Frage, [ob die Deutschen aussterben], das ist für mich eine, die ich an allerletzter Stelle stelle, weil dieses ist mir, also so wie sie hier gestellt wird, verhältnismäßig wurscht.\nRenate Schmidt"
    "Die Zukunft des Islam in diesem, unserem Land, in Deutschland, gestalten wir; wir, die hier geboren und aufgewachsen sind, wir, die wir die deutsche Sprache sprechen und die Mentalität dieses Volkes kennen. Entscheidend ist, dass wir in diesem Land unsere Religionsfreiheit haben (auch wenn wir sie sehr häufig vor Gericht erst erstreiten müssen) und dass es keinen Grund gibt, nicht aktiv an der Neugestaltung dieser Gesellschaft mitzuwirken. Ich glaube nicht, dass es unmöglich ist, dass der Bundeskanzler im Jahre 2020 ein in Deutschland geborener und aufgewachsener Muslim ist, dass wir im Bundesverfassungsgericht einen muslimischen Richter oder eine muslimische Richterin haben, dass im Rundfunkrat auch ein muslimischer Vertreter sitzt, der die Wahrung der verfassungsmäßig garantierten Rechte der muslimischen Bürger sichert. Dieses Land ist unser Land, und es ist unsere Pflicht, es positiv zu verändern. Mit der Hilfe Allahs werden wir es zu unserem Paradies auf der Erde machen, um es der islamischen Ummah und der Menschheit insgesamt zur Verfügung zu stellen. Allah verändert die Lage eines Volkes erst, wenn das Volk seine Lage ändert!\n~Ibrahim El-Zayat",
    "Im Jahr 2100 wird es in Deutschland 35 Millionen Türken geben. Die Einwohnerzahl der Deutschen wird dann bei ungefähr 20 Millionen liegen. Das, was Kamuni Sultan Süleyman mit der Belagerung Wiens 1529 begonnen hat, werden wir über die Einwohner, mit unseren kräftigen Männern und gesunden Frauen, verwirklichen.\n~Vural Öger",
    "Es ist gut so, dass wir Deutsche bald in der Minderheit sind.\n~Stefanie von Berg",
    "Nur weil jemand vergewaltigt, beraubt oder hoch kriminell ist, ist das kein Grund zur Abschiebung. Wir sollten uns stattdessen seiner annehmen und ihn akzeptieren, wie er ist. Es gibt Menschenrechte.\n~Margarete Bause",
    "Die Leute werden endlich Abschied nehmen von der Illusion, Deutschland gehöre den Deutschen.\n~Çigdem Akkaya",
    "Vaterlandsliebe fand ich stets zum kotzen. Ich wusste mit Deutschland noch nie etwas anzufangen und weiß es bis heute nicht.\n~Robert Habeck",
    "Natürlich gehört der Islam zu Deutschland, und natürlich gehören Muslime zu Deutschland. Und ich finde, darüber können wir ganz schön froh sein. Es wäre sehr langweilig, wenn wir nur mit uns zu tun hätten.\n~Katrin Göring-Eckardt"
]

ls_english = [
    "Four years of Trump and the attack on the heart of American democracy show that right-wing populists in power are not disenchanting themselves. That must be a lesson for all of us. \n~Baerbock",
    "Germany is a problem because the Germans are more hardworking, more disciplined and more talented than the rest of Europe. That will lead to 'imbalances' again and again. But this can be counteracted by diverting as much money as possible out of Germany. It is no matter what, it can also be wasted radically - the main thing is that the Germans don't have it. The world has already been saved. \n~Joschka Fischer ",
    "I have never sung the German national anthem and I will not do it as a minister either. \n~Jürgen Trittin",
    "Germany has to be enclosed from the outside and heterogenized, quasi-diluted, from the inside by the influx of foreigners. \n~Joschka Fischer",
    "Germans are 'non-migrants' - nothing more! ... Turkey is my second home, I've been politics in Turkey for 20 years. \n~Claudia Roth",
    "We know your inner state. We have a look and the necessary sensitivity for this. And since we know you, we will no longer rely on you. We go our way and it is painful and full of thorns, but successful in the end ... - You only have the chance to live with us. A life without us will no longer exist for you. The Ibrahims, Stefanos, Marios, Laylas and Sorayas are German reality .... - You will not be able to prevent it from happening soon a judge of Turkish origin will pass judgment on you, a Pakistani doctor will cure your illnesses, a Tamil parliament will help to pass your laws ... You will not modernize and humanize society, but we will do it for you! - You are with this painful one Process only onlookers, annoying onlookers! We will change German society in East and West! \n~M. Walid Nakschbandi ",
    "It is not about right or wrong in the immigration debate, we are primarily concerned with pushing back the German population in this country! \n~Board of the Greens",
    "Germany is disappearing more and more every day, and I think that's just great. \n~Jürgen Trittin",
    "I wanted France to reach as far as the Elbe and Poland to border directly on France. \n~Sieglinde Frieß",
    "Migration is a fact in Frankfurt. If that doesn't suit you, you have to move somewhere else. \n~Nargess Eskandari-Grünberg",
    "Basically: We, the Greens, must ensure that as many foreigners as possible come to "
    "Germany. When you are in Germany, we have to fight for your right to vote. When we have achieved that, we will have the share of the vote that we need to change this republic. \n~Daniel Cohn-Bendit",
    "German heroes should simply kill the world, like mad dogs. \n~Joschka Fischer",
    "The abolition of the oath formula 'For the good of the German people' is decided unanimously in the NRW state parliament. \n~Arif Ünal",
    "The question of [whether the Germans are dying out] is for me one that I put at the very last point, because I don't care much about it, as it is asked here. \nRenate Schmidt"
    "We are shaping the future of Islam in this, our country, in Germany; we who were born and raised here, we who speak the German language and know the mentality of this people. What matters is that we have ours in this country Have religious freedom (even if we very often have to fight for it first in court) and that there is no reason not to actively participate in the reorganization of this society. I do not believe that it is impossible for the Federal Chancellor to be born in Germany in 2020 and a grown-up Muslim is that we have a Muslim judge in the Federal Constitutional Court, that the Broadcasting Council also has a Muslim representative who ensures that the constitutionally guaranteed rights of Muslim citizens are respected. This country is our country and it is our duty to change it in a positive way, with the help of Allah we will make it our paradise on earth for the sake of it Islamic Ummah and humanity at large. Allah only changes the situation of a people when the people change their situation! \n~Ibrahim El-Zayat ",
    "In the year 2100 there will be 35 million Turks in Germany. The population of the Germans will then be around 20 million. What Kamuni Sultan Suleyman began with the siege of Vienna in 1529, we will be about the inhabitants, with our strong men and healthy women, realize. \n~Vural Öger ",
    "It is a good thing that we Germans will soon be in the minority. \n~Stefanie von Berg",
    "Just because someone is raped, robbed or highly criminal is not a reason for deportation. We should instead embrace him and accept him for who he is. There are human rights. \n~Margarete Bause ",
     "The people will finally say goodbye to the illusion that Germany belongs to the Germans. \n~Çigdem Akkaya",
     "I always found love of my fatherland puke. I never knew what to do with Germany and still don't know. \n~Robert Habeck",
     "Of course Islam belongs to Germany, and of course Muslims belong to Germany. And I think we can be very happy about that. It would be very boring if we only had anything to do with ourselves. \n~Katrin Göring-Eckardt" 
]